import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
import { Toaster } from 'sonner'
import Header from '@/components/header';

export const metadata = {
  title: "FinSight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
{/* header */}
<Header/>
        <main className="min-h-screen">{children} </main>
       <Toaster  position="top-right"  richColors />
        {/* footer */}
        <footer className="bg-pink-900 py-12">
          <div className="container mx-auto text-center text-white px-4">
            <p>Made with ❤️ by Durga</p>
          </div>
        </footer>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
